<?php

/**
 * @file
 * Install, update and uninstall functions for the uky_base installation profile.
 */

use Drupal\user\Entity\User;
use Drupal\shortcut\Entity\Shortcut;
use Symfony\Component\Yaml\Yaml;
use Drupal\Core\Config\FileStorage;
use Drupal\Core\Entity\EntityTypeManagerInterface;

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function uky_base_install()
{
  // Assign user 1 the "administrator" role.
  $user = User::load(1);
  $user->roles[] = 'administrator';
  $user->save();

  // We install some menu links, so we have to rebuild the router, to ensure the
  // menu links are valid.
  \Drupal::service('router.builder')->rebuildIfNeeded();

  // Populate the default shortcut set.
  $shortcut = Shortcut::create([
    'shortcut_set' => 'default',
    'title' => t('Add content'),
    'weight' => -20,
    'link' => ['uri' => 'internal:/node/add'],
  ]);
  $shortcut->save();

  $shortcut = Shortcut::create([
    'shortcut_set' => 'default',
    'title' => t('All content'),
    'weight' => -19,
    'link' => ['uri' => 'internal:/admin/content'],
  ]);
  $shortcut->save();
}

// Update Hooks ___________________________________________________________________

/**
 * Updates uky base to enable uky maps module.
 *
 */
function uky_base_update_9201() {
  include_once dirname(__FILE__) . '/hooks/9201.install';
}

/**
 * Install D10-related modules and uninstall color, and rdf.
 */
function uky_base_update_9202() {
  include_once dirname(__FILE__) . '/hooks/9202.install';
}

/**
 * Update the field_page_header configuration.
 */
function uky_base_update_9203() {
  include_once dirname(__FILE__) . '/hooks/9203.install';
}

/**
 * Enable the CKEditor 4 module
 */
function uky_base_update_9204() {
  include_once dirname(__FILE__) . '/hooks/9204.install';
}

/**
 * Enable the person_sidenav view
 */
function uky_base_update_9205() {
  include_once dirname(__FILE__) . '/hooks/9205.install';
}

/**
 * Updates uky base to enable uky 50 50 slab paragraph, webform paragraph, and pullquote paragraph
 */
function uky_base_update_9206() {
  include_once dirname(__FILE__) . '/hooks/9206.install';
}

/**
 * Update function to modify the views.view.frontpage configuration to diable the /node view.
 */
function uky_base_update_9207() {
  include_once dirname(__FILE__) . '/hooks/9207.install';
}

/**
 * Uninstall obsolete permissions_filter module
 */
function uky_base_update_9208() {
  include_once dirname(__FILE__) . '/hooks/9208.install';
}

/**
 * uky_base - CKEditor5
 */
function uky_base_update_9209() {
  include_once dirname(__FILE__) . '/hooks/9209.install';
}

/**
 * uky_base - Update People section menu view block offset to hide nodes
 */
function uky_base_update_9210() {
  include_once dirname(__FILE__) . '/hooks/9210.install';
}

/**
 * uky_base - Update file.settings.yml for file sanitization.
 */
function uky_base_update_9211() {
  include_once dirname(__FILE__) . '/hooks/9211.install';
}

/**
 * uky_base - Install UKY Base Mega Menu
 */
function uky_base_update_9212() {
  include_once dirname(__FILE__) . '/hooks/9212.install';
}

/**
 * uky_base - Install Limestone Module
 */
function uky_base_update_9213() {
  include_once dirname(__FILE__) . '/hooks/9213.install';
}

/**
 * uky_base - Set Event dates to required
 */
function uky_base_update_9214() {
  include_once dirname(__FILE__) . '/hooks/9214.install';
}

/**
 * uky_base - Set permissions for the view unpublished module for platform roles.
 */
function uky_base_update_9215() {
  include_once dirname(__FILE__) . '/hooks/9215.install';
}

/**
 * uky_base - Set permissions for the file replace module for platform roles.
 */
function uky_base_update_9216() {
  include_once dirname(__FILE__) . '/hooks/9216.install';
}

/**
 * uky_base - Install config for mobile sidebar nav on events, news, and people.
 */
function uky_base_update_9217() {
  include_once dirname(__FILE__) . '/hooks/9217.install';
}

/**
 * uky_base - Updating config of field group settings for content editors
 */
function uky_base_update_9218() {
  include_once dirname(__FILE__) . '/hooks/9218.install';
}

/**
 * uky_base - Setting optional end date for events date field
 */
function uky_base_update_9219() {
  include_once dirname(__FILE__) . '/hooks/9219.install';
}

/**
 * uky_base - Adding WebP image styling option for persons content type profile image
 */
function uky_base_update_9220() {
  include_once dirname(__FILE__) . '/hooks/9220.install';
}

/**
 * uky_base - Add utility menu block to mobile utility nav region
 */
function uky_base_update_9221() {
  include_once dirname(__FILE__) . '/hooks/9221.install';
}

/**
 * uky_base - Update event content_teaser view to only include upcoming events and not past events
 */
function uky_base_update_9222() {
  include_once dirname(__FILE__) . '/hooks/9222.install';
}

/**
 * uky_base - Adding CSV and Zip files to allowed file types on platform
 */
function uky_base_update_9223() {
  include_once dirname(__FILE__) . '/hooks/9223.install';
}

/**
 * Add page, block, sidebar nav for past events
 */
function uky_base_update_9224() {
  include_once dirname(__FILE__) . '/hooks/9224.install';
}

/**
 * uky_base - Adding linkblue link to login form
 */
function uky_base_update_9225() {
  include_once dirname(__FILE__) . '/hooks/9225.install';
}  

/**
 * uky_base - Adding max file size for audio, video and images
 */
function uky_base_update_9226() {
  include_once dirname(__FILE__) . '/hooks/9226.install';
}

/**
 * uky_base - Uninstall xmlsitemap, install simple_sitemap, and configure it.
 */
function uky_base_update_9227() {
  include_once dirname(__FILE__) . '/hooks/9227.install';
}

/**
 * uky_base - Add RSS feeds for news/events
 */
function uky_base_update_9228() {
  include_once dirname(__FILE__) . '/hooks/9228.install';
}

/**
 * uky_base - Install draggable views and import config for the directory sorting view.
 */
function uky_base_update_9229() {
  include_once dirname(__FILE__) . '/hooks/9229.install';
}

/**
* uky_base - Remove ignored pathauto words
 */
function uky_base_update_9230() {
  include_once dirname(__FILE__) . '/hooks/9230.install';
}

/**
 * uky_base - Setting Who can register accounts to administator only
 */
function uky_base_update_9231() {
  include_once dirname(__FILE__) . '/hooks/9231.install';
}

/**
 * uky_base - Adding content reviewer role
 */
function uky_base_update_9232() {
  include_once dirname(__FILE__) . '/hooks/9232.install';
}

/**
 * uky_base - Add sticky override perm to content manager role. 
 */
function uky_base_update_9233() {
  include_once dirname(__FILE__) . '/hooks/9233.install';
}

/**
 * uky_base - Redo hooks from 9220 and 9221 for path.
 */
function uky_base_update_9234() {
  include_once dirname(__FILE__) . '/hooks/9234.install';
}

/**
 * uky_base - Adding 12 hour date formats
 */
function uky_base_update_9235() {
  include_once dirname(__FILE__) . '/hooks/9235.install';
}

/**
 * uky_base - Sort past events by date (desc)
 */
function uky_base_update_9236() {
  include_once dirname(__FILE__) . '/hooks/9236.install';
}

/**
 * uky_base - Role-based permissions for People view
 */
function uky_base_update_9237() {
  include_once dirname(__FILE__) . '/hooks/9237.install';
}

/**
 * uky_base - Enable Gin admin theme and Gin Login
 */
function uky_base_update_9238() {
  include_once dirname(__FILE__) . '/hooks/9238.install';
}

/**
 * uky_base - Set paragraph fields to stable widget and default to closed.
 */
function uky_base_update_9239() {
  include_once dirname(__FILE__) . '/hooks/9239.install';
}

/**
 * uky_base - Update breadcrumb settings to not be on homepage.
 */
function uky_base_update_9240() {
  include_once dirname(__FILE__) . '/hooks/9240.install';
}

/**
 * uky_base - Create new Site Owner role.  
 */
function uky_base_update_9241() {
  include_once dirname(__FILE__) . '/hooks/9241.install';
}

/**
 * uky_base - Install new uky_base_admin module 
 */
function uky_base_update_9242() {
  include_once dirname(__FILE__) . '/hooks/9242.install';
}

/**
 * uky_base - Install new uky_base_paragraph_testimonial module 
 */
function uky_base_update_9243() {
  include_once dirname(__FILE__) . '/hooks/9243.install';
}

/**
 * uky_base - Install new uky_base_paragraph_in_page_alert module 
 */
function uky_base_update_9244() {
  include_once dirname(__FILE__) . '/hooks/9244.install';
}

/**
 * uky_base - Update uky_maps embederator
 */
function uky_base_update_9245() {
  include_once dirname(__FILE__) . '/hooks/9245.install';
}

/**
 * uky_base - Install eck listing view
 */
function uky_base_update_9246() {
  include_once dirname(__FILE__) . '/hooks/9246.install';
}

/**
 * uky_base - Place emergency alert block if it isn't there already
 */
function uky_base_update_9247() {
  include_once dirname(__FILE__) . '/hooks/9247.install';
}

/**
 * uky_base - Enable uky_base_paragraphs_separator module
 */
function uky_base_update_9248() {
  include_once dirname(__FILE__) . '/hooks/9248.install';
}

/**
 * uky_base - Enable uky_base_eck_page_header_overlay module and update the field on page content type.
 */
function uky_base_update_9249() {
  include_once dirname(__FILE__) . '/hooks/9249.install';
}

/**
 * uky_base - Set permissions for new paragraph types
 */
function uky_base_update_9250() {
  include_once dirname(__FILE__) . '/hooks/9250.install';
}

/**
 * uky_base - Update hook to order paragraph order
 */
function uky_base_update_9251() {
  include_once dirname(__FILE__) . '/hooks/9251.install';
}

/**
 * uky_base - Update hook add hero image size selector
 */
function uky_base_update_9252() {
  include_once dirname(__FILE__) . '/hooks/9252.install';
}

/**
 * uky_base - Update hook to change carousel image to full width view mode
 */
function uky_base_update_9253() {
  include_once dirname(__FILE__) . '/hooks/9253.install';
}

/**
 * uky_base - Update hook to change taxonomy filtering for content teaser grids to term number (only runs on views that are default platform)
 */
function uky_base_update_9254() {
  include_once dirname(__FILE__) . '/hooks/9254.install';
}

/**
 * uky_base - Enable config_log and config_log_views
 */
function uky_base_update_9255() {
  include_once dirname(__FILE__) . '/hooks/9255.install';
}