<?php

use Drupal\user\Entity\User;
use Drupal\shortcut\Entity\Shortcut;
use Symfony\Component\Yaml\Yaml;
use Drupal\Core\Config\FileStorage;

  //empty string to store a message
  $message = "";

  //names of the configs to be updated
  $config_names = ['block_visibility_groups.block_visibility_group.person_node', 'views.view.person_sidenav', 'block.block.views_block__person_sidenav_block_1'];
  //obtain the path of these configs using getPath service
  $path_to_module = \Drupal::service('extension.path.resolver')->getPath('module', 'uky_base_node_person');

  //if the config is available, parse the yaml config and set it to the configFactory
  foreach ($config_names as $config_name) {
    $config_path1 = $path_to_module . "/config/install/" . $config_name . ".yml";
    $config_path2 = $path_to_module . "/config/optional/" . $config_name . ".yml";

    if (file_exists($config_path1)) {
      $data = Yaml::parseFile($config_path1);
      \Drupal::configFactory()->getEditable($config_name)->setData($data)->save(TRUE);
      $message .= "Config" . $config_name . "installed .\n";
    } elseif (file_exists($config_path2)) {
      $data = Yaml::parseFile($config_path2);
      \Drupal::configFactory()->getEditable($config_name)->setData($data)->save(TRUE);
      $message .= "Config" . $config_name . "installed .\n";
    } else {
      $message .= "Config update didn't work\n";
    }
  }

  return $message;
  