<?php

use Drupal\user\Entity\User;
use Drupal\shortcut\Entity\Shortcut;
use Symfony\Component\Yaml\Yaml;
use Drupal\Core\Config\FileStorage;

  // Specify the paths of the configuration files.
  $config_files = [
    'profiles/custom/uky_base/modules/custom/uky_base_node_person/config/optional/block.block.ukd8_views_block__duplicate_of_person_sidenav_block_1.yml',
    'profiles/custom/uky_base/modules/custom/uky_base_node_person/config/optional/views.view.duplicate_of_person_sidenav.yml',
    'profiles/custom/uky_base/modules/custom/uky_base_node_news/config/optional/block.block.ukd8_views_block__duplicate_of_news_sidenav_block_1.yml',
    'profiles/custom/uky_base/modules/custom/uky_base_node_news/config/optional/views.view.duplicate_of_news_sidenav.yml',
    'profiles/custom/uky_base/modules/custom/uky_base_node_event/config/optional/block.block.ukd8_views_block__duplicate_of_events_sidenav_block_1.yml',
    'profiles/custom/uky_base/modules/custom/uky_base_node_event/config/optional/views.view.duplicate_of_events_sidenav.yml',
  ];

  // Get the config factory service.
  $config_factory = \Drupal::service('config.factory');

  // Import each specified configuration file.
  foreach ($config_files as $config_file) {
    // Check if the file exists before importing.
    if (file_exists($config_file)) {
      // Load the configuration object.
      $config_name = str_replace('.yml', '', basename($config_file));
      $config = $config_factory->getEditable($config_name);
      
      // Parse YAML file.
      $yaml_content = file_get_contents($config_file);
      $parsed_yaml = Yaml::parse($yaml_content);
      
      // Import configuration.
      $config->setData($parsed_yaml)->save();
    }
    else {
      \Drupal::logger('uky_base')->error('Config file %file does not exist.', ['%file' => $config_file]);
    }
  }