<?php

use Drupal\user\Entity\User;
use Drupal\shortcut\Entity\Shortcut;
use Symfony\Component\Yaml\Yaml;
use Drupal\Core\Config\FileStorage;

  // Load the configuration for the field.
  $config = \Drupal::configFactory()->getEditable('ldap_authentication.settings');
  
  // Update the file_extensions setting.
  $config->set('loginUIPasswordTxt', 'Enter your linkblue password.<br /><p>Need Assistance? <a href="https://www.uky.edu/linkblue/">Visit the linkblue help page</a></p>')
         ->save();
 