<?php

use Drupal\user\Entity\User;
use Drupal\shortcut\Entity\Shortcut;
use Symfony\Component\Yaml\Yaml;
use Drupal\Core\Config\FileStorage;

  // Define the permissions to be added to roles.
  $view_permissions = [
    'view paragraph content in_page_alert',
    'view paragraph content separator',
    'view paragraph content testimonial',
  ];

  $create_update_delete_permissions = [
    'create paragraph content in_page_alert',
    'create paragraph content separator',
    'create paragraph content testimonial',
    'delete paragraph content in_page_alert',
    'delete paragraph content separator',
    'delete paragraph content testimonial',
    'update paragraph content in_page_alert',
    'update paragraph content separator',
    'update paragraph content testimonial',
  ];

  // Load roles using the RoleStorageInterface service.
  $role_storage = \Drupal::entityTypeManager()->getStorage('user_role');

  // Add permissions to 'authenticated' role.
  $authenticated_role = $role_storage->load('authenticated');
  if ($authenticated_role) {
    user_role_grant_permissions($authenticated_role->id(), $view_permissions);
  }

  // Add permissions to 'anonymous' role.
  $anonymous_role = $role_storage->load('anonymous');
  if ($anonymous_role) {
    user_role_grant_permissions($anonymous_role->id(), $view_permissions);
  }

  // Add additional permissions to 'content_editor' role.
  $content_editor_role = $role_storage->load('content_editor');
  if ($content_editor_role) {
    user_role_grant_permissions($content_editor_role->id(), $create_update_delete_permissions);
  }